import { Check, X } from "lucide-react";
import { useEffect, useState } from "react";
import type { Tutor } from "../data/tutors";

export function RequestTutorDialog({ tutor, open, onClose }: { tutor?: Tutor; open: boolean; onClose: () => void }) {
  const [step, setStep] = useState<"form"|"ready"|"success">("form");
  useEffect(() => { if (open) setStep("form"); }, [open]);
  if (!open) return null;
  return <div className="dialog-backdrop" role="presentation" onMouseDown={(event)=>event.target===event.currentTarget&&onClose()}><section className="request-dialog" role="dialog" aria-modal="true" aria-labelledby="request-title"><button type="button" className="dialog-close" aria-label="Close request" onClick={onClose}><X/></button>{step==="success"?<div className="request-success"><span><Check/></span><p className="eyebrow">Preview complete</p><h2 id="request-title">Demo request captured</h2><p>This is currently a preview of the future tutor-request experience. No information has been sent or stored.</p><button type="button" className="button button-primary" onClick={onClose}>Done</button></div>:<><p className="eyebrow">Frontend preview</p><h2 id="request-title">{step==="ready"?"Your tutor request is ready":`Request ${tutor?.name ?? "tutor support"}`}</h2>{step==="ready"?<div className="request-ready"><p>Tutors Academy can review your requirement and help identify suitable tutors.</p><div className="demo-notice">Submitting below only demonstrates the future success state. No request will be sent.</div><button type="button" className="button button-primary" onClick={()=>setStep("success")}>Submit Requirement</button><button type="button" className="text-button" onClick={()=>setStep("form")}>Edit details</button></div>:<form className="request-form" onSubmit={(event)=>{event.preventDefault();setStep("ready")}}><p>Share how Tutors Academy should contact you about this illustrative requirement.</p><label>Parent or student name<input required name="name" autoComplete="name"/></label><div className="form-two"><label>Email<input required type="email" name="email" autoComplete="email"/></label><label>Phone<input required type="tel" name="phone" autoComplete="tel"/></label></div><fieldset><legend>Preferred contact method</legend><div className="choice-row"><label><input type="radio" name="contact" value="phone" defaultChecked/> Phone</label><label><input type="radio" name="contact" value="email"/> Email</label><label><input type="radio" name="contact" value="whatsapp"/> WhatsApp</label></div></fieldset><label>Additional requirements<textarea name="requirements" rows={4} placeholder="Tell us anything else that would help."/></label><button className="button button-primary" type="submit">Review Request</button></form>}</>}</section></div>;
}